export { default as OpenEye } from './auth-screen/open-eye'
export { default as CloseEye } from './auth-screen/close-eye'
export { default as CheckBoxTick } from './auth-screen/check-box.tick'
export { default as WhiteBackArrow } from './auth-screen/white-back-aarow'
export { default as FilledBar } from './auth-screen/register-screen/filled-baar'
export { default as UnFilledBar } from './auth-screen/register-screen/unfilled-baar'
export { default as OutlineCalender } from './auth-screen/register-screen/outlined-calender'
export { default as AppLogo } from './auth-screen/app-logo'
export { default as DrawerOpenSvg } from "./home-screen/drawer-open-svg"
export { default as DropwDownSvgDown } from "./common/drop-down-down-svg"
export { default as BackGroundLine } from "./common/background-line-svg"
export { default as DrawerPencil } from "./drawer/drawer-pencile"
export { default as ForwardArrow } from "./drawer/forwar-arrow"
export { default as CrossIconSvg } from "./common/cross-icon-svg"
export { default as DrawerAppointmentSvg } from "./drawer/appointment-svg"
export { default as DrawerInsuranceSvg } from "./drawer/insurance-svg"
export { default as DrawerPrescription } from "./drawer/prescription-svg"
export { default as DrawerListYourPractiseSvg } from "./drawer/list-your-practise-svg"
export { default as DrawerAboutUsSvg } from "./drawer/about-us-svg"
export { default as DrawerPoliciesSvg } from "./drawer/policies-svg"
export { default as DrawerContactUsSvg } from "./drawer/contact-us-svg"
export { default as DrawerChangePassword } from "./drawer/change-password-svg"
export { default as DrawerDeleteAccountSvg } from "./drawer/delete-account-svg"
export { default as DrawerLogoutSvg } from "./drawer/logout-svg"
export { default as DeleteAccountArrowSvg } from "./drawer/delete-account-arrow-svg"
export { default as DeleteModalSvg } from "./drawer/delete-modal-svg"
export { default as BackArrowSvg } from "./common/back-arrow-svg"
export { default as LocationSvg } from "./drawer/contact_us_svg/location-svg"
export { default as EmailSvg } from "./drawer/contact_us_svg/email-svg"
export { default as PhoneSvg } from "./drawer/contact_us_svg/phone-svg"
export { default as ConnectSvg } from "./drawer/about_us_svg/connect-svg"
export { default as TrustSvg } from "./drawer/about_us_svg/trust-svg"
export { default as ConnectEyeSvg } from "./drawer/about_us_svg/connect-eye-svg"
export { default as MiniBottomBorder } from "./drawer/about_us_svg/mini-bottom-border-svg"
export { default as PartnerSvg } from "./drawer/about_us_svg/partner-svg"
export { default as SearchSvg } from "./appointment/search-svg"
export { default as OrangeSvgFilter } from "./appointment/orange-filter-svg"
export { default as DrVisitTypeSvg } from "./appointment/de-visit-type-svg"
export { default as TranlsationSvg } from "./appointment/translatetion-svg"
export { default as StarSvg } from "./appointment/star-svg"
export { default as CopySvg } from "./appointment/copy-svg"
export { default as FilePickupSvg } from "./appointment/file-pickup-svg"
export { default as InfoPinSvg } from "./appointment/info-pin-svg"
export { default as PinSvg } from "./appointment/pin-svg"
export { default as PipeSvg } from "./common/pipe-svg"
export { default as EditPencilIconSvg } from "./drawer/edit-pencil-icon-svg"
export { default as LinearGradientSvg } from "./book-appointment/gradient-svg"
export { default as TakePhotoSvg } from "./drawer/take-photo-svg"
export { default as UploadPhotoSvg } from "./drawer/upload-photo-svg"
export { default as BlackCrossIconSvg } from "./common/black-cross-icon"
export { default as SuccessModalSvg } from "./drawer/success-modal-svg"
export { default as FailureModalSvg } from "./drawer/failure-modal-svg"
export { default as NoDoctorAvailableSvg } from "./common/no-doctor-available"
export { default as NoAppointmentFoundSvg } from "./common/no-appointment-found-svg"
export { default as NoInternetSvg } from "./common/no-internet-svg"
export { default as UploadDocSvg } from "./common/upload-doc-svg"
export { default as EditButtonSvg } from "./common/edit-button-svg"
export { default as DeleteButtonSvg } from "./common/delete-button"


// Doctore
export { default as StatStatusScop } from "./home-screen/stat-statusScop";
export { default as StatHospBuild } from "./home-screen/stat-Hospbuild";
export { default as StatCalenderSvg } from './home-screen/stat-calender';
export { default as HeartRateMonitor } from './home-screen/heart-monitor';
export { default as DrawerDashBoardSvg } from './drawer/dashboard-svg';
export { default as DrawerPatientSvg } from './drawer/drawer-patient-svg';
export { default as DrawerSettinSvg } from './drawer/setting-svg';
export { default as OrangeForwarArrow } from './drawer/orange-forward-arrow';
export { default as OrangePlusSvg } from './drawer/orange-plus-svg';


//profile completion
export { default as DoctorSvg } from "./profile-completion/doctor-svg"
export { default as FilledCompletionSvg } from "./profile-completion/filled-completion-svg"
export { default as UnfilledCompletionSvg } from "./profile-completion/unfilled-completion-svg"
export { default as GreenTickIndicationSvg } from "./profile-completion/green-tick-indication-svg"
export { default as ProfileInsuranceIncompleteSvg } from "./profile-completion/profile-insurance-svg-incomplete"
export { default as ProfileInsuranceCompleteSvg } from "./profile-completion/profile-insurance-complete-svg"
export { default as ProfileTimeSlotIncompleteSvg } from "./profile-completion/profile-time-slot-incomplete-svg"
export { default as ProfileTimeSlotCompleteSvg } from "./profile-completion/profile-time-slot-compplete-svg"
export { default as LogoutSvg } from "./profile-completion/logout-svg"
export { default as ProfileCompleteSvg } from "./profile-completion/profile-complete-svg"
export { default as ProfileIncompleteSvg } from "./profile-completion/profile-incomplete-svg"
export { default as UnderVerificationSvg } from "./profile-completion/under-verificatiob-svg"
export { default as ProfileVerifiedSvg } from "./profile-completion/profile-verified-svg"
export { default as ProfileRejectedSvg } from "./profile-completion/profile-rejected-svg"
export { default as profileVerifiedTouchSoonSvg } from './profile-completion/profile-verified-touch-soon-svg'
export { default as ProfileVerificationRejectedSvg } from './profile-completion/profile-verification-rejected-svg'
export { default as ProfileVerificationSuccessSvg } from './profile-completion/profile-verification-success-svg'
export { default as DrawerRightArrowSvg } from "./drawer/drawer-right-arrow"
export { default as TimeSlotSvg } from "./profile-completion/time-slot-svg"
export { default as AgeSvg } from './drawer/age-svg';
export { default as OffToggle } from './drawer/off-toggle';
export { default as OnToggle } from './drawer/on-toggle';


//competed profile on drawer screen
export { default as PersonalSvg } from "./drawer/completed-profile/personal-info-svg"
export { default as ProfessionalInfoSvg } from "./drawer/completed-profile/professional-info-svg"
export { default as practiseInfoSvg } from "./drawer/completed-profile/practise-info-svg"
export { default as AdditionalInfoSvg } from "./drawer/completed-profile/additional-info-svg"
export { default as CLockSvg } from './drawer/clock-svg';
export { default as RefreshSvg } from './drawer/refresh-svg';
export { default as BrowseSvg } from './drawer/browse-svg';
export { default as PdfSvg } from './drawer/pdf-svg';
export { default as FilterSvg } from './drawer/filter-svg';
export { default as YellowCalenderSvg } from './drawer/yellow-calender-svg';
export { default as TodaySvg } from './appointment/today-svg';
export { default as WeekSvg } from './appointment/week-svg';
export { default as StatusBlock } from './appointment/status-block';
export { default as PrescDeleteSvg } from './drawer/prescription-delete-svg';
export { default as KnobDownArrowSvg } from './common/knob-arrow-down';
export { default as AppointmentFilterSvg } from "./common/appointment-filter-svg"